--DROP TABLE IF EXISTS users CASCADE;
--DROP TABLE IF EXISTS cities CASCADE;
--DROP TABLE IF EXISTS matches CASCADE;
--DROP TABLE IF EXISTS messages CASCADE;
--DROP TABLE IF EXISTS photos CASCADE;
--DROP TABLE IF EXISTS user_photo CASCADE;
--DROP TABLE IF EXISTS chats CASCADE;
--DROP TABLE IF EXISTS deleted_chats CASCADE;
--DROP TABLE IF EXISTS user_interests CASCADE;
--DROP TABLE IF EXISTS user_roles CASCADE;


--CREATE EXTENSION IF NOT EXISTS postgis;

-- 0. Таблица города
--CREATE TABLE cities
--(
--    id        SERIAL PRIMARY KEY,
--    city_name VARCHAR(255),
--    location  geometry(Point, 4326),
--    source    VARCHAR(25),
--    accuracy int
--);



--
---- 1. Таблица users
--CREATE TABLE users (
--                       id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                       username         VARCHAR(50)  NOT NULL,
--                       email            VARCHAR(30) UNIQUE,
--                       gender           VARCHAR(10),
--                       preferred_gender VARCHAR(10),
--                       birth_date       DATE,
--                       about_me         VARCHAR(200),
--                       city_id          INT,
--                       status           VARCHAR(10),
--                       provider         VARCHAR(255) NOT NULL,
--                       external_id      VARCHAR(255),
--                       email_pending    BOOLEAN DEFAULT TRUE,
--                       FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE SET NULL,
--                       CHECK (
--                               email IS NULL OR (
--                                       TRIM(email) != '' AND
--                                       email ~ '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
--                               )
--                           )
--);
--
---- 2. Таблица user_roles
--CREATE TABLE user_roles (
--                            id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                            user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
--                            roles   VARCHAR(20)
--);
--
---- 3. Таблица matches
--CREATE TABLE matches (
--                         id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                         created_at     DATE,
--                         first_user_id  INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
--                         second_user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
--                         match_status   VARCHAR(10)
--);
--
---- Уникальный индекс на пару пользователей в матче

--CREATE UNIQUE INDEX idx_unique_match
--    ON matches (first_user_id, second_user_id);

--CREATE UNIQUE INDEX idx_unique_match
--    ON matches (first_user_id, second_user_id);
--
---- 4. Таблица chats
--CREATE TABLE chats (
--                       id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                       sender_id   BIGINT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
--                       receiver_id BIGINT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
--                       sent_at     TIMESTAMP NOT NULL
--);
--
---- Уникальный индекс на пару отправитель/получатель (чтобы не было дубликатов чатов)
--CREATE UNIQUE INDEX idx_chat_pair ON chats (
--                                            LEAST(sender_id, receiver_id),
--                                            GREATEST(sender_id, receiver_id)
--    );
--
---- 5. Таблица messages
--CREATE TABLE messages (
--                          id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                          content        VARCHAR(300),
--                          sent_at        TIMESTAMP DEFAULT NOW() NOT NULL,
--                          sender_id      INTEGER REFERENCES users (id) ON DELETE CASCADE,
--                          chat_id        INTEGER REFERENCES chats (id) ON DELETE CASCADE,
--                          is_read        VARCHAR(10) DEFAULT 'FALSE',
--                          basket         BOOLEAN   DEFAULT FALSE
--);
--
---- 6. Таблица photos
--CREATE TABLE photos (
--                        id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                        file_path VARCHAR(500),
--                        file_name VARCHAR(255),
--                        file_size INT,
--                        file_type VARCHAR(10)
--);
--
---- 7. Таблица user_photo
--CREATE TABLE user_photo (
--                            id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                            user_id  INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
--                            photo_id INT NOT NULL REFERENCES photos (id) ON DELETE CASCADE
--);
--
---- 8. Таблица user_interests
--CREATE TABLE user_interests (
--                                id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                                user_id  INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
--                                interest VARCHAR(20)
--);
--
---- 9. Таблица deleted_chats
--CREATE TABLE deleted_chats (
--                               user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
--                               chat_id    BIGINT NOT NULL REFERENCES chats (id) ON DELETE CASCADE,
--                               deleted_at TIMESTAMP DEFAULT NOW(),
--                               PRIMARY KEY (user_id, chat_id)
--);



--INSERT INTO users (username,
--                   email,
--                   gender,
--                   preferred_gender,
--                   birth_date,
--                   about_me,
--                   city_id,
--                   status,
--                   provider,
--                   external_id,
--                   email_pending)
--VALUES ('testUserMary', 'Mary@example.com', 'WOMEN', 'MEN', '1990-01-15', 'Привет! Обожаю пиво и покер!', 1, 'COMPLETE', 'GITHUB', '12345',
--        FALSE),
--       ('testUserAlena', 'Alena@example.com', 'WOMEN', 'MEN', '1990-01-15', 'Привет! Люблю котов', 1, 'COMPLETE',
--        'GITHUB', '22345',
--        FALSE),
--       ('testUserAnna', 'Anna@example.com', 'WOMEN', 'MEN', '1990-01-15', 'Привет! Обнимаю весь мир', 1, 'COMPLETE',
--        'GITHUB', '32345',
--        FALSE),
--       ('testUserJulia', 'Julia@example.com', 'WOMEN', 'MEN', '1990-01-15', 'Привет! Коллеги добрый день!', 1, 'COMPLETE', 'GITHUB',
--        '42345',
--        FALSE),
--       ('testUserEvgeny', 'Evgeny@example.com', 'MEN', 'WOMEN', '1990-01-15', 'Привет! Люблю этот мир', 1, 'COMPLETE',
--        'GITHUB', '52345',
--        FALSE),
--       ('testUserNikita', 'Nikita@example.com', 'MEN', 'WOMEN', '1990-01-15', 'Привет! Apple правит миром', 1,
--        'COMPLETE', 'GITHUB', '72345',
--        FALSE),
--       ('testUserVlad', 'Vlad@example.com', 'MEN', 'WOMEN', '1990-01-15', 'Привет! Когда нибудь я отвечу, но точно не сегодня', 1, 'COMPLETE',
--        'GITHUB', '82345',
--        FALSE);



SELECT *
FROM user_photo
WHERE user_id = 35;

--insert into photos (file_path, file_name, file_size, file_type)
--values ('/images/testuserJulia.jpeg', 'testuserJulia.jpeg', 1000, 'jpeg');
--insert into photos (file_path, file_name, file_size, file_type)
--values ('/images/testuserAnna.jpeg', 'testuserAnna.jpeg', 1000, 'jpeg');
--insert into photos (file_path, file_name, file_size, file_type)
--values ('/images/testuserAlena.jpeg', 'testuserAlena.jpeg', 1000, 'jpeg');
--insert into photos (file_path, file_name, file_size, file_type)
--values ('/images/testuserMary.jpeg', 'testuserMary.jpeg', 1000, 'jpeg');
--insert into photos (file_path, file_name, file_size, file_type)
--values ('/images/testuserVlad.jpeg', 'testuserVlad.jpeg', 1000, 'jpeg');
--insert into photos (file_path, file_name, file_size, file_type)
--values ('/images/testuserNikita.jpeg', 'testuserNikita.jpeg', 1000, 'jpeg');
--insert into photos (file_path, file_name, file_size, file_type)
--values ('/images/testuserEvgeny.jpeg', 'testuserEvgeny.jpeg', 1000, 'jpeg');

--insert into user_photo (user_id, photo_id) values (4, 34);
--insert into user_photo (user_id, photo_id) values (3, 35);
--insert into user_photo (user_id, photo_id) values (2, 36);
--insert into user_photo (user_id, photo_id) values (1, 37);
--insert into user_photo (user_id, photo_id) values (7, 38);
--insert into user_photo (user_id, photo_id) values (6, 39);
--insert into user_photo (user_id, photo_id) values (5, 40);


--ТЕСТЫ

--TRUNCATE  TABLE  matches cascade;
--TRUNCATE  TABLE  chats cascade;
--TRUNCATE  TABLE  deleted_chats cascade;
--TRUNCATE  TABLE  messages cascade;
--
--insert into matches (first_user_id, second_user_id, match_status) values (2, 9, 'LIKE');


delete from users where id = 31;
delete from users where id = 34;




