--DROP TABLE IF EXISTS users CASCADE;
--DROP TABLE IF EXISTS cities CASCADE;
--DROP TABLE IF EXISTS matches CASCADE;
--DROP TABLE IF EXISTS messages CASCADE;
--DROP TABLE IF EXISTS photos CASCADE;
--DROP TABLE IF EXISTS user_interests CASCADE;
--DROP TABLE IF EXISTS user_photo CASCADE;
--DROP TABLE IF EXISTS messages CASCADE;
--DROP TABLE IF EXISTS chats CASCADE;
--
--
--CREATE EXTENSION IF NOT EXISTS postgis;
--CREATE TABLE cities
--(
--    id        SERIAL PRIMARY KEY,
--    city_name VARCHAR(255),
--    location  geometry(Point, 4326)
--);
--
--
--
--CREATE TABLE users
--(
--    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    username         varchar(50) NOT NULL,
--    email            varchar(30) UNIQUE,
--    gender           varchar(10),
--    preferred_gender varchar(10),
--    birth_date       date,
--    about_me         varchar(200),
--    city_id          INTEGER REFERENCES cities (id)
--);
--
--
--
--CREATE TABLE matches
--(
--    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    created_at     date,
--    first_user_id  INTEGER REFERENCES users (id) ,
--    second_user_id INTEGER REFERENCES users (id),
--    match_status   boolean DEFAULT FALSE
--
--);
--CREATE UNIQUE INDEX idx_unique_match
--    ON matches (first_user_id, second_user_id);
--CREATE TABLE messages
--(
--    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    content  varchar(300),
--    sent_at  date,
--    sender   INTEGER REFERENCES users (id),
--    receiver INTEGER REFERENCES users (id),
--    match    INTEGER REFERENCES matches (id),
--    message_status varchar (10)
--);
--
--CREATE TABLE photos
--(
--    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    file_path varchar(500),
--    file_name varchar(255),
--    file_size int,
--    file_type varchar(10)
--);
--
--CREATE TABLE user_photo
--(
--    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    user_id  int,
--    photo_id int,
--    FOREIGN KEY (user_id) REFERENCES users (id),
--    FOREIGN KEY (photo_id) REFERENCES photos (id)
--);
--
--
--CREATE TABLE user_interests
--(
--    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    user_id  int,
--    interest varchar(20),
--    FOREIGN KEY (user_id) REFERENCES users (id)
--
--);


--DROP TABLE IF EXISTS messages CASCADE ;
--DROP TABLE IF EXISTS chats CASCADE;
--DROP TABLE IF EXISTS deleted_chats CASCADE;
--CREATE TABLE chats (
--                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                       sender_id BIGINT NOT NULL REFERENCES users(id),
--                       receiver_id BIGINT NOT NULL REFERENCES users(id),
--                       sent_at TIMESTAMP NOT NULL
--);
--CREATE UNIQUE INDEX idx_chat_pair ON chats (
--                                            LEAST(sender_id, receiver_id),
--                                            GREATEST(sender_id, receiver_id)
--    );
--
--CREATE TABLE messages (
--                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                          content VARCHAR(500),
--                          sent_at TIMESTAMP NOT NULL,
--                          sender_id BIGINT NOT NULL REFERENCES users(id),
--                          chat_id BIGINT NOT NULL REFERENCES chats(id),
--                          message_status BOOLEAN
--);

--CREATE TABLE deleted_chats (
--                               user_id BIGINT REFERENCES users(id),
--                               chat_id BIGINT REFERENCES chats(id),
--                               deleted_at TIMESTAMP DEFAULT NOW(),
--                               PRIMARY KEY (user_id, chat_id)
--);


SELECT *
FROM chats c
WHERE
    (c.sender_id = 3 OR c.receiver_id = 3)
  AND NOT EXISTS (
        SELECT 1
        FROM deleted_chats dc
        WHERE dc.chat_id = c.id
          AND dc.user_id = 3  -- именно для пользователя 2
    );

SELECT *
FROM chats c
WHERE
    ((c.sender_id = 3 OR c.receiver_id = 2) AND c.id = 3)
  AND NOT EXISTS (
        SELECT 1
        FROM deleted_chats dc
        WHERE dc.chat_id = c.id
          AND dc.user_id = 3  -- именно для пользователя 2
    );


SELECT *
FROM deleted_chats
WHERE user_id = 2 AND chat_id = 3;

SELECT *
FROM users
ORDER BY id asc;






