--
--SELECT u.*
--FROM users u
--         JOIN user_interests ui on u.id = ui.user_id
--WHERE interest IN (SELECT interest
--                   FROM user_interests
--                   GROUP BY interest
--                   HAVING COUNT(*) > 1)
--GROUP BY u.id
--;


--CREATE TABLE tests
--(
--    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    city_name varchar(50) NOT NULL,
--    location GEOGRAPHY(POINT, 4326)
--);
--
--INSERT INTO tests (city_name, location)
--VALUES ('User1', ST_GeographyFromText('POINT(37.6173 55.7558)'));


SELECT *
FROM users
ORDER BY id asc;


--SELECT u.*
--FROM users u
--         JOIN user_interests ui on u.id = ui.user_id
--WHERE interest IN (SELECT interest
--                   FROM user_interests
--                   WHERE interest = 'TRAVEL'
--                   GROUP BY interest
--                   HAVING COUNT(*) > 1)
--GROUP BY u.id


--CREATE TABLE cities
--(
--    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    city_name varchar(50) NOT NULL,
--    latitude  float,
--    longitude float
--);

SELECT u.*
FROM users u
         JOIN cities c on u.city_id = c.id
WHERE ST_DWithin(
        c.location,
        ST_SetSRID(ST_MakePoint(37.6173, 55.7558), 4326),
        0.7)
  AND gender = 'MAN';

SELECT u.*
FROM users u
         JOIN cities c on u.city_id = c.id
         JOIN user_interests i on u.id = i.user_id
WHERE ST_DWithin(
        c.location,
        ST_SetSRID(ST_MakePoint(37.6173, 55.7558), 4326),
        0.5)
  AND gender = 'MAN'
  AND i.interest = 'TRAVEL';


--
--SELECT *
--FROM matches
--WHERE first_user_id = 1
--    AND second_user_id = 2
--   OR first_user_id = 2
--    AND second_user_id = 1
--;
--
--INSERT INTO matches (first_user_id, second_user_id)
--VALUES (1, 2);
--
--SELECT *
--FROM matches
--WHERE first_user_id = 2
--    AND second_user_id = 1
--   OR first_user_id = 1
--    AND second_user_id = 2;
--
--INSERT INTO matches (first_user_id, second_user_id, match)
--VALUES (2, 1, true);
--UPDATE matches
--SET match = true
--WHERE first_user_id = 1
--  AND second_user_id = 2;
--
--
--SELECT *
--FROM matches
--WHERE first_user_id = 1
--    AND second_user_id = 3
--   OR first_user_id = 3
--    AND second_user_id = 1;
--
--INSERT INTO matches (first_user_id, second_user_id)
--VALUES (1, 3);
--
--
--SELECT *
--FROM matches
--WHERE first_user_id = 3
--    AND second_user_id = 1
--   OR first_user_id = 1
--    AND second_user_id = 3;
--
--INSERT INTO matches (first_user_id, second_user_id, match)
--VALUES (3, 1, true);
--UPDATE matches
--SET match = true
--WHERE first_user_id = 1
--  AND second_user_id = 3;
--
--SELECT *
--FROM matches
--WHERE first_user_id = 4
--    AND second_user_id = 1
--   OR first_user_id = 1
--    AND second_user_id = 4;
--INSERT INTO matches (first_user_id, second_user_id)
--VALUES (4, 1);
--
--
---- ЗАПРОС МЕТЧЕЙ УЗЕРА 1
--SELECT *
--FROM matches
--WHERE first_user_id = 1
--  AND match = true;
--
---- ЗАПРОС КОМУ ОТПРАВИЛ ЛАЙКИ УЗЕР 4 И НЕ ПОЛУЧИЛ МЕТЧА
--SELECT *
--FROM matches
--WHERE first_user_id = 4
--  AND match = false;
--
---- ЗАПРОС КОМУ ПОНРАВИЛСЯ ЮЗЕР 1
--SELECT *
--FROM matches
--WHERE second_user_id = 1
--  AND match = false;
--
--UPDATE matches
--SET match = false
--WHERE second_user_id = 1;
--DELETE
--FROM matches
--WHERE first_user_id = 1
--  AND second_user_id = 2;
--
--BEGIN;
--UPDATE matches
--SET match = true
--WHERE first_user_id = 1
--  AND second_user_id = 4;
--

DELETE FROM matches WHERE first_user_id = 1 AND second_user_id = 2;