DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS interests CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS photos CASCADE;
DROP TABLE IF EXISTS user_interests CASCADE;
CREATE TABLE cities
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name varchar(50) NOT NULL,
    latitude  float,
    longitude float
);

CREATE TABLE users
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  varchar(50) NOT NULL,
    password  varchar(50) NOT NULL,
    email     varchar(30) UNIQUE,
    gender    varchar(10),
    birthdate date,
    city_id   INTEGER REFERENCES cities (id),
    photos    int[],
    interests int[]

);

CREATE TABLE interests
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(200)
);
CREATE TABLE matches
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     date,
    first_user_id  INTEGER REFERENCES users (id),
    second_user_id INTEGER REFERENCES users (id)
);
CREATE TABLE messages
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content  varchar(300),
    sent_at  date,
    sender   INTEGER REFERENCES users (id),
    receiver INTEGER REFERENCES users (id),
    match    INTEGER REFERENCES matches (id)
);

CREATE TABLE photos
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path varchar(500),
    user_id   INTEGER REFERENCES users (id)
);

CREATE TABLE user_interests
(
    user_id     int,
    interest_id int,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (interest_id) REFERENCES interests (id)
);
